// dirrectory where .tim files will be saved
const path="//TF-MILLO03/Users/experiment/Documents/phase_meas";
// mqtt server's IP
const mqtt_broker="192.168.1.170";

// variables need to be global to be used in multiple acquisitions
var acq_num = 0; 

// This is the script entry point
function EventRunScript()
{
	prep_acq();
	start_acq();
	acq_num = 0;
}

function prep_acq()
{
	// This configuration is generated by TimeLab by clicking "Save script..." in the measurement configuration dialog box
	AcqClearParams();

	AcqSetParam("Measure Stability",             "True");
	AcqSetParam("Measure PM Noise",              "True");
	AcqSetParam("Measure AM Noise",              "True");
	AcqSetParam("Trace",                         "THIS IS THE DISPLAYED TRACE NAME");
	AcqSetParam("Notes",                         "");
	AcqSetParam("Duration",                      "10");
	AcqSetParam("Duration Type",                 "1");             // 1=seconds, 2=minutes, 3=hours, 4=days
	AcqSetParam("Device ID",                     "");              // Leave blank to use first available device
	AcqSetParam("Auto Clock",                    "True");
	AcqSetParam("Scale PN to DUT",               "False");
	AcqSetParam("Scale Jitter to DUT",           "False");
	AcqSetParam("Overlapped",                    "False");
	AcqSetParam("Attenuate Instrument Spurs",    "True");
	AcqSetParam("ADC Clock",                     "119.35E6");
	AcqSetParam("Cancel CM Drift",               "False");
	AcqSetParam("FFT 0",                         "3-1");
	AcqSetParam("FFT 1",                         "4-2");
	AcqSetParam("Stability Ch",                  "3-1");
	AcqSetParam("Ch 1 Label",                    "HM");
	AcqSetParam("Ch 2 Label",                    "HM");
	AcqSetParam("Ch 3 Label",                    "WR");
	AcqSetParam("Ch 4 Label",                    "WR");
	AcqSetParam("Ch 1 Enabled",                  "True");
	AcqSetParam("Ch 2 Enabled",                  "True");
	AcqSetParam("Ch 3 Enabled",                  "True");
	AcqSetParam("Ch 4 Enabled",                  "True");
	AcqSetParam("Ch 1 Stability Ref",            "0");
	AcqSetParam("Ch 2 Stability Ref",            "1");
	AcqSetParam("Ch 3 Stability Ref",            "0");
	AcqSetParam("Ch 4 Stability Ref",            "3");
	AcqSetParam("Ch 1 Noise Ref",                "0");
	AcqSetParam("Ch 2 Noise Ref",                "1");
	AcqSetParam("Ch 3 Noise Ref",                "0");
	AcqSetParam("Ch 4 Noise Ref",                "1");
	AcqSetParam("Ch 1 Freq Mode",                "0");
	AcqSetParam("Ch 2 Freq Mode",                "0");
	AcqSetParam("Ch 3 Freq Mode",                "0");
	AcqSetParam("Ch 4 Freq Mode",                "0");
	AcqSetParam("Ch 1 Rounding",                 "0.1");
	AcqSetParam("Ch 2 Rounding",                 "0.1");
	AcqSetParam("Ch 3 Rounding",                 "0.1");
	AcqSetParam("Ch 4 Rounding",                 "0.1");
	AcqSetParam("Ch 1 Specified Frequency",      "10.000000");
	AcqSetParam("Ch 2 Specified Frequency",      "10.000000");
	AcqSetParam("Ch 3 Specified Frequency",      "10.000000");
	AcqSetParam("Ch 4 Specified Frequency",      "10.000000");
	AcqSetParam("Ref Ch",                        "1");
	AcqSetParam("L(f) Max Scale",                "-20");
	AcqSetParam("L(f) Min Scale",                "-170.0");
	AcqSetParam("PN Max Offset",                 "1E7");
	AcqSetParam("PN Min Offset",                 "0.1");
	AcqSetParam("Input Splitter (DUT)",          "1");
	AcqSetParam("Input Splitter (Ref)",          "0");
	AcqSetParam("Add'l PN Gain",                 "0.0");
	AcqSetParam("Add'l AM Gain",                 "0.0");
	AcqSetParam("DUT Freq",                      "");
	AcqSetParam("Auto DUT",                      "True");
	AcqSetParam("Decimation",                    "460");
	AcqSetParam("Spur Threshold",                "6.0");
	AcqSetParam("Spur Min Hz",                   "0.0");
	AcqSetParam("FFT Win #",                     "0");             // 0=HFT95 flat top, 1=Hann
	AcqSetParam("Rate Index",                    "7");             // 0=50 kHz at 1K points/sec, 1=50 kHz/100, 2=5 kHz/1K, 3=5 kHz/100, 4=500/1K, 5=500/100, 6=50/100, 7=50/10, 8=5/10, 9=5/1
	AcqSetParam("Output Decimation",             "2");
	AcqSetParam("Bin Density",                   "29");
	AcqSetParam("Bin Threshold",                 "4");
	AcqSetParam("Trace History",                 "1");
	AcqSetParam("Stop Condition",                "0");             // 0=stop when measurement done, 1=run until interrupted
	AcqSetParam("Warnings Treated as Errors",    "False");
	AcqSetParam("Clock Signal Generator",        "0");
	AcqSetParam("Clock Signal Monitor",          "0");
	AcqSetParam("Clock Oscillator Offset",       "10000");
	AcqSetParam("VR SS",                         "False");
	AcqSetParam("DCS",                           "False");
	AcqSetParam("I/O Blocks",                    "32");
	AcqSetParam("I/O Block Size",                "1048576");
	AcqSetParam("Dither Level",                  "1");
	AcqSetParam("Syx Estimator #",               "0");
	AcqSetParam("Reset ADCs",                    "True");
	AcqSetParam("Role",                          "1");             // 0=manual config 1=1D1R, 2=1D2RI, 3=1D2RE, 4=2D1R, 5=3D1R, 6=3HAT, 7=1DX1R
	AcqSetParam("Ext Converter",                 "0");             // 0=none, 1=low-side LO, 2=high-side LO, 3=N divider
	AcqSetParam("Ext LO",                        "0");
	AcqSetParam("Ext N",                         "1");
	AcqSetParam("Autoscale Noise",               "False");
	ScriptShowTTY(false);
}

function start_acq()
{
	// wait for locksweep to be done
	if (!FileExecuteWait("c:\\Program Files\\Mosquitto\\mosquitto_sub.exe", " -h "+mqtt_broker+" -t locksweeping -C 1")) {
		ScriptEnd(); // stop on error
	}
	AcqStartAcquisition("Microchip 53100A ...", 
		true);
}

// This function is called at the end of each acquisition
function EventAcqDone()
{
	FileSave(path, "save_" + acq_num + ".tim");
	++acq_num;
	// send signal acquisition done to allow lovksweep reboot
	if (!FileExecute("c:\\Program Files\\Mosquitto\\mosquitto_pub.exe", " -h "+mqtt_broker+" -t locksweep_now -m acq_done")) {
		ScriptEnd(); // stop on error
	}
	FileCloseAllPlots();
	prep_acq();
	start_acq();
	
	if (acq_num >= 10000) {
		ScriptEnd();
	}
}
